package com.hubject.datex.convert.model.datarecord;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Code {
    SUCCESS("000"),
    HUBJECT_SYSTEM_ERROR("001"),
    HUBJECT_DATABASE_ERROR("002"),
    DATA_TRANSACTION_ERROR("009"),
    UNAUTHORIZED_ACCESS("017"),
    INCONSISTENT_EVSE_ID("018"),
    INCONSISTENT_EVCO_ID("019"),
    SYSTEM_ERROR("021"),
    DATA_ERROR("022"),
    QR_CODE_AUTHENTICATION_FAILED_INVALID_CREDENTIALS("101"),
    RFID_AUTHENTICATION_FAILED_INVALID_UID("102"),
    RFID_AUTHENTICATION_FAILED_CARD_NOT_READABLE("103"),
    PLC_AUTHENTICATION_FAILED_INVALID_EVCO_ID("105"),
    NO_POSITIVE_AUTHENTICATION_RESPONSE("106"),
    QR_CODE_APP_AUTHENTICATION_FAILED_TIME_OUT_ERROR("110"),
    PLC_AUTHENTICATION_FAILED_INVALID_UNDERLYING_EVCO_ID("120"),
    PLC_AUTHENTICATION_FAILED_INVALID_CERTIFICATE("121"),
    PLC_AUTHENTICATION_FAILED_TIME_OUT_ERROR("122"),
    EVCO_ID_LOCKED("200"),
    NO_VALID_CONTRACT("210"),
    PARTNER_NOT_FOUND("300"),
    PARTNER_DID_NOT_RESPOND("310"),
    SERVICE_NOT_AVAILABLE("320"),
    SESSION_IS_INVALID("400"),
    COMMUNICATION_TO_EVSE_FAILED("501"),
    NO_EV_CONNECTED_TO_EVSE("510"),
    EVSE_ALREADY_RESERVED("601"),
    EVSE_ALREADY_IN_USE_WRONG_TOKEN("602"),
    UNKNOWN_EVSE_ID("603"),
    EVSE_ID_IS_NOT_HUBJECT_COMPATIBLE("604"),
    EVSE_OUT_OF_SERVICE("700");

    private final String value;

    @JsonValue
    public String getValue() {
        return value;
    }
}
